#!/usr/bin/env bash

TASKS_DIR="tasks"

if [ $# -eq 0 ]; then
  echo "Usage: $(basename "$0") <TASK> [ARGS...]"
  echo "Available tasks:"
  echo "  bash"
  echo "$(ls "$TASKS_DIR")" | sed 's/^/  /'
  exit 1
fi

if [ "$1" == "bash" ]; then
  TASK="/usr/bin/env $@"
else
  TASK="${TASKS_DIR}/$@"
fi

docker-compose \
  -f docker-compose.yml -f docker-compose.tasks.yml \
  run --rm task_runner $TASK
