#!/usr/bin/env sh

set -euo pipefail

DUMP="./backup/db.sql.gz"
[ ! -e "$DUMP" ] && echo "No dump file exists" && exit 1

gzip -dc "$DUMP" | \
  mysql -h mysql -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" \
    && echo "Database restored from dump"
